# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character] 
success_symbol = '[󰄾](bold green)' 
error_symbol = '[󰄾](bold red)'
vimcmd_symbol = '[V](bold green) '

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[golang]
format = '[[Go](bold cyan)-$version](cyan)'
